/* Generated by cbindgen — do not edit by hand. */

#ifndef HUUB_C_API_H
#define HUUB_C_API_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Return code for solver-status queries and for entry points that don't
 * return a handle. Mirrors `huub::solver::Status` plus an explicit error
 * code for FFI failures.
 */
typedef enum {
  /**
   * A satisfying assignment was found.
   */
  HUUB_RESULT_SATISFIED = 0,
  /**
   * The model has no solution.
   */
  HUUB_RESULT_UNSATISFIABLE = 1,
  /**
   * All solutions have been enumerated (optimization or all-solutions
   * mode). Treat as SAT for satisfaction queries.
   */
  HUUB_RESULT_COMPLETE = 2,
  /**
   * Search terminated without proving SAT/UNSAT (time limit, conflict
   * budget, interrupt).
   */
  HUUB_RESULT_UNKNOWN = 3,
  /**
   * Solve has not been run yet on this handle.
   */
  HUUB_RESULT_NOT_SOLVED = 4,
  /**
   * An error occurred. See `huub_last_error()` for details.
   */
  HUUB_RESULT_ERROR = 5,
} HuubResult;

/**
 * Comparator for `huub_model_add_linear`.
 */
typedef enum {
  HUUB_REL_OP_LE = 0,
  HUUB_REL_OP_LT = 1,
  HUUB_REL_OP_GE = 2,
  HUUB_REL_OP_GT = 3,
  HUUB_REL_OP_EQ = 4,
  HUUB_REL_OP_NE = 5,
} HuubRelOp;

/**
 * Opaque handle. C side only sees `HuubModel*`.
 */
typedef struct HuubModel HuubModel;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the last error message recorded on the calling thread, or
 * `NULL` if no error has occurred since the last successful call. The
 * returned pointer is valid until the next FFI call on this thread.
 */
const char *huub_last_error(void);

/**
 * Create a new model handle. Returns `NULL` on failure (call
 * `huub_last_error()`).
 */
HuubModel *huub_model_new(void);

/**
 * Free a model handle previously returned by `huub_model_new()`. Passing
 * `NULL` is a no-op.
 */
void huub_model_free(HuubModel *handle);

/**
 * Create a new integer decision variable with domain `[lb, ub]`. Returns
 * a non-negative variable id on success, or `-1` on error (call
 * `huub_last_error()` for details).
 */
int32_t huub_model_new_int_var(HuubModel *handle, int64_t lb, int64_t ub);

/**
 * Create a new Boolean decision variable. Returns a non-negative variable
 * id on success, or `-1` on error.
 */
int32_t huub_model_new_bool_var(HuubModel *handle);

/**
 * Post a linear constraint: `sum(coeffs[i] * int_var[var_ids[i]]) op rhs`.
 *
 * `var_ids` and `coeffs` are arrays of length `n`. All ids must refer to
 * integer variables previously returned by `huub_model_new_int_var()`.
 *
 * Returns `HuubResult::Satisfied` on success (the constraint was posted
 * without immediate conflict), `HuubResult::Unsatisfiable` if posting
 * the constraint immediately proved the model infeasible, or
 * `HuubResult::Error` on FFI failure.
 */
HuubResult huub_model_add_linear(HuubModel *handle,
                                 const int32_t *var_ids,
                                 const int64_t *coeffs,
                                 uintptr_t n,
                                 HuubRelOp op,
                                 int64_t rhs);

/**
 * Lower the model and run a single-worker satisfaction search.
 *
 * `time_limit_seconds <= 0` disables the wall-clock limit. Returns one of
 * `Satisfied`, `Unsatisfiable`, `Unknown`, or `Error`. After a successful
 * solve, call `huub_model_value_int` / `huub_model_value_bool` to read
 * the assignment.
 *
 * Once called, the model transitions to a "solved" state and further
 * mutations (var creation, constraint posting) will fail.
 */
HuubResult huub_model_solve(HuubModel *handle, double time_limit_seconds);

/**
 * Read the value of an integer variable from the most recent solve.
 * Writes to `*out` and returns `Satisfied` on success; returns
 * `NotSolved` / `Error` on failure (leaving `*out` untouched).
 */
HuubResult huub_model_value_int(HuubModel *handle, int32_t var_id, int64_t *out);

/**
 * Read the value of a Boolean variable from the most recent solve.
 * Same contract as `huub_model_value_int`.
 */
HuubResult huub_model_value_bool(HuubModel *handle, int32_t var_id, bool *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HUUB_C_API_H */
